Add sprig FuncMap to templates
volatiletech/sqlboiler pull request #1086
Opened 2022-02-15 05:39 UTC by ccakes

Resolves #659 

This adds the well-known [Sprig](https://pkg.go.dev/github.com/Masterminds/sprig/v3) template functions to the sqlboiler template renderer.

In addition, and in a separate commit as it might be a little more controversial, this also adds a config option that can only be set by someone embedding sqlboiler as a library to allow the caller to add their own `template.FuncMap` to make extending simpler without needing to fork.

Feedback welcome. If the `UserFuncs` concept is acceptable to the maintainers let me know and I'll add some test coverage and documentation before we merge.

2022-02-15 11:16 UTC, stephenafamo commented
These make sense. However, I think it makes more sense to move the `UserFuncs` to a different PR.

2022-02-15 11:18 UTC, ccakes commented
No worries, I can do that 👍

2022-02-15 18:16 UTC, ccakes commented
I've split this up so we only have Sprig here, the `UserFuncs` are now implemented in #1088

2022-02-17 10:47 UTC, stephenafamo requested changes

2022-02-17 10:47 UTC, stephenafamo commented on boilingcore/templates.go
>  // add a function pointer here.
A little nitpicky, but I think it makes sense to update this comment too since it is no longer **all the functions**

2022-02-23 14:16 UTC, stephenafamo commented
Copied the changes to #1097 and added a few minor changes on top.

I'll close this and merge that.

2022-02-23 14:16 UTC, closed without merging